export const SET_TAB_VAL = "SET_TAB_VAL";

export const GET_LEAGUEDATA = "GET_LEAGUEDATA";
export const GET_LEAGUEDATA_INIT = "GET_LEAGUEDATA_INIT";
export const GET_LEAGUEDATA_SUCCESS = "GET_LEAGUEDATA_SUCCESS";
export const GET_LEAGUEDATA_FAIL = "GET_LEAGUEDATA_FAIL";

export const GET_PLAYERDATA = "GET_PLAYERDATA";
export const GET_PLAYERDATA_INIT = "GET_PLAYERDATA_INIT";
export const GET_PLAYERDATA_SUCCESS = "GET_PLAYERDATA_SUCCESS";
export const GET_PLAYERDATA_FAIL = "GET_PLAYERDATA_FAIL";
