export const SET_TAB_VAL = "SET_TAB_VAL";
export const SET_LEAGUE_INFO = "SET_LEAGUE_INFO";
export const RESET_LEAGUE_INFO = "RESET_LEAGUE_INFO";

export const GET_LEAGUEDATA = "GET_LEAGUEDATA";
export const GET_LEAGUEDATA_INIT = "GET_LEAGUEDATA_INIT";
export const GET_LEAGUEDATA_SUCCESS = "GET_LEAGUEDATA_SUCCESS";
export const GET_LEAGUEDATA_FAIL = "GET_LEAGUEDATA_FAIL";

export const GET_HISTORYDATA = "GET_HISTORYDATA";
export const GET_HISTORYDATA_INIT = "GET_HISTORYDATA_INIT";
export const GET_HISTORYDATA_SUCCESS = "GET_HISTORYDATA_SUCCESS";
export const GET_HISTORYDATA_FAIL = "GET_HISTORYDATA_FAIL";

export const GET_PLAYERDATA = "GET_PLAYERDATA";
export const GET_PLAYERDATA_INIT = "GET_PLAYERDATA_INIT";
export const GET_PLAYERDATA_SUCCESS = "GET_PLAYERDATA_SUCCESS";
export const GET_PLAYERDATA_FAIL = "GET_PLAYERDATA_FAIL";
